apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: my-volume
      mountPath: "/var/www/html"
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: my-pvc

.......


spec:
  containers:
  - name: my-container
    image: nginx
    volumeMounts:
    - name: my-volume
      mountPath: "/var/www/html"
  volumes:
  - name: my-volume
    configMap:
      name: html-content
      items:
      - key: index.html
        path: index.html

