apiVersion: v1
kind: Pod
metadata:
  name: my-pod1
spec:
  containers:
  - name: container1
    image: httpd:latest
    volumeMounts:
    - name: my-volume-1
      mountPath: "/usr/local/apache2/htdocs/"
  volumes:
  - name: my-volume-1
    persistentVolumeClaim:
      claimName: my-pvc


