apiVersion: v1
kind: Pod
metadata:
  name: my-pod1
spec:
  containers:
  - name: container1
    image: httpd
    volumeMounts:
    - name: my-volume-1
      mountPath: "/var/www/html"
  volumes:
  - name: my-volume-1
    persistentVolumeClaim:
      claimName: my-pvc


