apiVersion: v1
kind: Pod
metadata:
  name: my-pod2
spec:
  containers:
  - name: container2
    image: httpd:latest
    volumeMounts:
    - name: my-volume-2
      mountPath: "/usr/local/apache2/htdocs"
  volumes:
  - name: my-volume-2
    persistentVolumeClaim:
      claimName: my-pvc



