apiVersion: v1
kind: Pod
metadata:
  name: my-pod2
spec:
  containers:
  - name: container2
    image: httpd:latest
    volumeMounts:
    - name: my-volume
      mountPath: "/usr/local/apache2/htdocs/"
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: my-pvc



